package dems;


/**
* dems/EventManagementServiceImpl.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EventManagementService.idl
* Saturday, February 29, 2020 7:23:19 o'clock PM EST
*/

public interface EventManagementServiceImpl extends EventManagementServiceImplOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EventManagementServiceImpl
