package dems;


/**
* dems/EventManagementServiceImplOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EventManagementService.idl
* Saturday, February 29, 2020 7:23:19 o'clock PM EST
*/

public interface EventManagementServiceImplOperations 
{
  String login (String userName);
  String addEvent (String eventID, String eventType, int bookingCapacity);
  String removeEvent (String eventID, String eventType);
  String listEventAvailability (String eventType);
  String bookEvent (String customerID, String eventID, String eventType);
  String getBookingSchedule (String customerID);
  String cancelEvent (String customerID, String eventID, String eventType);
  String swapEvent (String customerID, String eventID, String eventType, String oldEventID, String oldEventType);
  void shutdown ();
} // interface EventManagementServiceImplOperations
