package dems;

/**
* dems/EventManagementServiceImplHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EventManagementService.idl
* Saturday, February 29, 2020 7:23:19 o'clock PM EST
*/

public final class EventManagementServiceImplHolder implements org.omg.CORBA.portable.Streamable
{
  public dems.EventManagementServiceImpl value = null;

  public EventManagementServiceImplHolder ()
  {
  }

  public EventManagementServiceImplHolder (dems.EventManagementServiceImpl initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dems.EventManagementServiceImplHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dems.EventManagementServiceImplHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dems.EventManagementServiceImplHelper.type ();
  }

}
